services:
  aurorabot:
    container_name: Bot
    image: mlikiowa/napcat-docker:latest

    environment:
      - ACCOUNT=3552638520

    ports:
      - "3001:3001"
      - "6099:6099"

    tmpfs:
      - /app/nt_db:size=64m    # 真正 tmpfs 挂载，纯内存，限制 64MB

    volumes:
      - ./config/nt_config:/app/napcat/config

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

    restart: unless-stopped
  # app:
  #   build: .
  #   image: aurora-bot:latest
  #   container_name: AuroraBot
  #   restart: always
  #   depends_on:
  #     - aurorabot
