version: "3"
services:
    aurorabot:
        environment:
            - ACCOUNT=3552638520
            - WS_ENABLE=true
        ports:
            - 3001:3001
            - 8082:8082
            - 6099:6099
        container_name: Bot
        restart: always
        image: mlikiowa/napcat-docker:latest
    # app:
    #     build: .
    #     restart: always
    #     container_name: AuroraBot-app
    #     depends_on:
    #         - napcat
    #     image: aurora-bot:latest




