version: "3"
services:
    AuroraBot:
        environment:
            - ACCOUNT=3552638520
        ports:
            - 3001:3001
            - 6099:6099
        container_name: AuroraBot
        restart: always
        image: mlikiowa/napcat-docker:latest
    app:
        build: .
        restart: always
        container_name: AuroraBot
        depends_on:
            - AuroraBot
        image: aurora-bot:latest
